version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: welcome_123
    #volumes:
      #- mongodb_data:/data/db

  htmlstorageapi:
    build: .
    container_name: htmlstorageapi
    ports:
      - "5000:8080"
    depends_on:
      - mongodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

#volumes:
  #mongodb_data:
    #driver: local
